"""2.0

Revision ID: 0439dea53079
Revises: 6a5653cfee9e
Create Date: 2024-02-23 21:19:15.894998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0439dea53079'
down_revision: Union[str, None] = '6a5653cfee9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blood_component_id', sa.Integer(), nullable=False),
    sa.Column('blood_amount', sa.Integer(), nullable=False),
    sa.Column('donor_amount', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('end_actual_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['blood_component_id'], ['blood_components.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors__recipient',
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('blood_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.PrimaryKeyConstraint('donor_id', 'recipient_id')
    )
    op.drop_table('demands')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blood_component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blood_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('donor_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_actual_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blood_component_id'], ['blood_components.id'], name='demands_blood_component_id_fkey'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name='demands_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='demands_pet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='demands_pkey')
    )
    op.drop_table('donors__recipient')
    op.drop_table('recipient')
    op.drop_table('donors')
    # ### end Alembic commands ###
