"""3

Revision ID: 1482d208c005
Revises: aefe0d34a61c
Create Date: 2024-02-23 19:04:33.451778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1482d208c005'
down_revision: Union[str, None] = 'aefe0d34a61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_types', sa.Column('icon', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_types', 'icon')
    # ### end Alembic commands ###
