"""empty message

Revision ID: 584a0e0439e5
Revises: e5ba4b2c95e2
Create Date: 2024-02-25 05:04:09.493339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584a0e0439e5'
down_revision: Union[str, None] = 'e5ba4b2c95e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.add_column('donors', sa.Column('date', sa.Date(), nullable=False))
    op.create_foreign_key(None, 'donors', 'clinics', ['clinic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donors', type_='foreignkey')
    op.drop_column('donors', 'date')
    op.drop_column('donors', 'clinic_id')
    # ### end Alembic commands ###
