"""empty message

Revision ID: 97a5b04488a1
Revises: f75df2b085bf
Create Date: 2024-02-24 12:29:31.557797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a5b04488a1'
down_revision: Union[str, None] = 'f75df2b085bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet__vaccinations', sa.Column('vaccination_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet__vaccinations', 'vaccination_date')
    # ### end Alembic commands ###
