"""first revision

Revision ID: aefe0d34a61c
Revises: 9a4584ad0776
Create Date: 2024-02-23 17:17:25.424809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefe0d34a61c'
down_revision: Union[str, None] = '9a4584ad0776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pet_blood_groups', 'blood_groups', ['blood_group_id'], ['id'])
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_constraint(None, 'pet_blood_groups', type_='foreignkey')
    # ### end Alembic commands ###
