"""empty message

Revision ID: bc4d1618bb7f
Revises: 0439dea53079
Create Date: 2024-02-24 00:03:06.522005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4d1618bb7f'
down_revision: Union[str, None] = '0439dea53079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_networks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_networks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_networks', type_='foreignkey')
    op.drop_column('user_networks', 'user_id')
    # ### end Alembic commands ###
