"""empty message

Revision ID: f75df2b085bf
Revises: e702b5d08d62
Create Date: 2024-02-24 09:48:48.702347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75df2b085bf'
down_revision: Union[str, None] = 'e702b5d08d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors__recipient', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'donors__recipient', 'clinics', ['clinic_id'], ['id'])
    op.alter_column('user_networks', 'telegram',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_networks', 'vk',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_networks', 'vk',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_networks', 'telegram',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'donors__recipient', type_='foreignkey')
    op.drop_column('donors__recipient', 'clinic_id')
    # ### end Alembic commands ###
